variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

default:
  image: maven:3.8.2-adoptopenjdk-16-openj9
  cache:
    key: maven-cache
    paths:
    - .m2/repository
  before_script:
    - apt-get update

stages:
  - build
  - test
  - test_master

build:
  stage: build
  script: 
    - mvn clean compile

test:
  stage: test
  script:
    - mvn -Dtestfx.robot=glass -Dtestfx.headless=true jacoco:prepare-agent test jacoco:report
    - cat marxbankfx/target/site/jacoco/index.html
    - cat core/target/site/jacoco/index.html

test_manual:
  stage: test_master
  script:
    - mvn -Dtestfx.robot=glass -Dtestfx.headless=true jacoco:prepare-agent test jacoco:report
    - cat marxbankfx/target/site/jacoco/index.html
    - cat core/target/site/jacoco/index.html
  when: manual

  
