variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

default:
  image: maven:3.8.2-adoptopenjdk-16-openj9
  cache:
    key: maven-cache
    paths:
    - .m2/repository
  before_script:
    - apt-get update
    - apt-get install -y xvfb libpangoft2-1.0-0

workflow: #Kjører kun når du pusher til en gren og når du sammenfletter med master
  rules:
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'

test:
  stage: test
  script: 
    - xvfb-run mvn "-DargLine=-Djava.awt.headless=true -DTestfx.robot=glass -Dtestfx.headless=true" clean jacoco:prepare-agent install jacoco:report
    - cat marxbankfx/target/site/jacoco-aggregate/index.html
    # - cat core/target/site/jacoco/index.html
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
